# -*- coding: utf-8 -*-
"""Exception Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_RChjvjPw9k7yeQIeELIFY6K0tFvCwx

# What is Exception
 ### Exception handling is Nothing But runtime Error and it occurs   due to incorrect implimention logic



> Excetion Handling
####  it is machanism through which we can handles the runtime errors



*   try
*   except


*   else
"""

a=10
b= 0

try:
  c=a/b
  print(c)
except:
  print("Exception is occured")

a= int(input("Enter the value of a:"))
b= int(input("Enter the value of b:"))

try:
  c=a/b
  print("Result",c)
except:
  print("can,t devide by zero")
print('hii')

a= int(input("Enter the value of a:"))
b= int(input("Enter the value of b:"))

try:
  c=a/b
  print("Result",c)
except:
  print("can't devide by zero")
else:
  print('hii')

