# -*- coding: utf-8 -*-
"""List Tupple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RPzgw3lurKIT3Kk859xWKGtwljortLd

# 1. Lists

- What are Lists?
- Lists vs Arrays
- Characteristics of a List
- How to create a List
- Access items from a List
- Editing items in a List
- Deleting items from a List
- Operations on Lists
- Functions on Lists

## What are Lists?

A **List** is a data type in Python where you can store multiple items under one name.

More technically, lists act like **dynamic arrays**, which means you can add or remove items on the fly.

### Example:

```python
L = [20, 'Jessa', 35.75, [30, 60, 90]]

print(L[0])  # 20
print(L[1])  # 'Jessa'
print(L[2])  # 35.75
print(L[3])  # [30, 60, 90]

## Array Vs Lists

- Fixed Vs Dynamic Size  
- Convenience → Heterogeneous  
- Speed of Execution  
- Memory

## How List Are Stored In Memory

## Characteristics of a List

- Ordered
- Changeable/Mutable
- Heterogeneous
- Can have duplicates
- are dynamic
- can be nested
- items can be accessed
- can contain any kind of objects in python

Creating a List
"""

# Empaty
print([])
# 1D -> Homogenus
print([1, 2, 3, 4])
# 2D
print([1,2,3,[4,5]])
# 3D
print([[[1,2],[3,4],[5,6],[7,8]]])
# Hetrogenous
print([1,'r','a',3.4,True])
# Using Type Converasion
print(list('hello'))

"""# Accessing Items From a list"""

#Indexing
l=[1,2,3,4,5]
print(l[0])
print(l[-1])
# Slicing
L=[1,2,3,4,5]
print(l[1:3])
print(l[::-1])

"""# Adding items to a List"""

# append
L=[1,2,3,4,5]
l.append(6)
print(l)

# Exctend
L=[1,2,3,4,5]
l.extend([6,7,8])
print(l)

l=[1,2,3,4,5]
l.append([6,7,8])
print(l)

l = [1,2,3,4,5]
l.extend("delhi")
print(l)

# Insert
l = [1,2,3,4,5]
l.insert(1,100)
print(l)

"""# Editing items ia a List"""

l=[1,2,3,4,5]

#editing with indexing
l[-1] = 500

# editing with slicing
l[1:4] = [200,300,400]

print(l)

"""# Deleting items From a list"""

# del
l1 =[1,2,3,4,5]

print(l)
# indexing
del l1[0]
print(l1)
#slicing
del l1[1:3]
print(l1)
# del l1
# print(l1)

# remove
l2 = [1,2,3,4,5]
l2.remove(5)
print(l2)

# pop
l3 = [1,2,3,4,5]

l3.pop(2)

print(l3)

# clear
l4 =[1,2,3,4,5]

l4.clear()

print(l4)

"""## Operation On List


*   Arithmetic
*   Membership

"""

# Arithmetic (+,-)
l1 = [1,2,3,4,5]

l2 = [6,7,8,9,10]

# Concattention
print(l1+l2)
print(l1*3)

#Membership
l1=[1,2,3,4,5]
l2=[1,2,3,[4,5]]

print(5 in l1)
print(5 not in l1)

"""# List Function"""

l1=[1,2,3,4,5]
l2=[1,2,3,[4,5]]
l3=[[[1,2],[3,4]],[[5,6],[7,8]]]

for i in l3:
  print(i)

# len/min/max/sorted
l5=[1,2,3,4,5]

print(len(l5))
print(min(l5))
print(max(l5))
print(sorted(l5))
print(sorted(l5,reverse=True))

# count
l6=[1,2,3,4,5,6,5,3,2]
l6.count(5)

# index
l7=[1,2,1,3,4,3,5,6]
l7.index(1)

# reverse
l8=[1,2,3,4,5,6,7,8]

#it paramaently reverses the list
l8.reverse()
print(l8)

# sort vs sorted
l9=[2,1,3,4,5]
print(l9)
print(sorted(l9))
print(l9)
l9.sort()
print(l9)

#copy
l10=[1,2,3,4,5]
print(l10)
print(id(l10))
l11=l10.copy()
print(l11)
print(id(l11))

"""## List Comprehension

List Comprehension provides a concise way of creating lists.

newlist = [expression for item in iterable if condition == True]

Advantages of List Comprehension

- More time-efficient and space-efficient than loops.
- Require fewer lines of code.
- Transforms iterative statement into a formula.

"""

# Add 1 to 10 numbers to a list
l=[]

for i in range(1,11):
  l.append(i)
print(l)

l= [i for i in range (1,11)]
print(l)

# Scaler multiplication on vector