# -*- coding: utf-8 -*-
"""OOP_Part_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__69raWvpSjyE9MoRJrKmsGwpQSyphVt

## Class Reletionship

*   Agregation
*   Inheritence
"""

class Customer:

    def __init__(self, name, gender, address):
        self.name = name
        self.gender = gender
        self.address = address

    def print_address(self):
        print(self.address.city, self.address.pin, self.address.state)


class Address:

    def __init__(self, city, pin, state):
        self.city = city
        self.pin = pin
        self.state = state


# Creating objects
add1 = Address('gurgaon', 122011, 'haryana')
cust = Customer('nitish', 'male', add1)

# Calling method
cust.print_address()



"""# Inheritence


*   What is Inheritence
*   Example

*   What Gets Inherited




"""

class User:

  def __init__(self):
    self.name = 'Ravi'

  def login(self):
     print('login')

class Student(User):

  # def __init__(self):
  #   super().__init__() # Call the parent class's __init__ method
  #   self.rollno = 100

  def enroll(self):
    print('enroll into the course')

u = User()
s = Student()

print(s.name)
s.login()
s.enroll()

#Class Diagram

"""# Whats gets  inherited


*   Constructor
*   Non Private Atribbutes

*   Non Private Methode




"""

# Constructor example

class Phone:
  def __init__(self, price, brand, camera):
    print('inside phone constructor')
    self.price = price
    self.brand = brand
    self.camera = camera

  def buy(self):
    print('buying a phone')

class SmartPhone(Phone):
  pass

s = SmartPhone(20000, 'samsung', 13)
s.buy()

# Constructor  Example 2
class Phone:

  def __init__ (self, price, brand, camera):
    print('inside phone constructor')
    self.price = price
    self.brand = brand
    self.camera = camera





class SmartPhone(Phone):
  def __init__(self,os,ram):
    self.os = os
    self.ram = ram
    print('inside smartphone constructor')


s = SmartPhone('android',8)

#Methode Overiding
class Phone:
  def __init__(self, price, brand, camera):
    print('inside phone constructor')
    self.price = price
    self.brand = brand
    self.camera = camera

  def buy(self):
    print('buying a phone')

class SmartPhone(Phone):
    def buy(self):
      print('buying a smartphone')

s = SmartPhone(20000, 'samsung', 13)
s.buy()

"""# super Keyword"""

class Phone:

  def __init__(self, price, brand, camera):
    print('inside phone constructor')
    self.price = price
    self.brand = brand
    self.camera = camera

  def buy(self):
    print('buying a phone')

class SmartPhone(Phone):
  def buy(self):
    print('buying a smartphone')
    #syntax to call parent method
    super().buy()

s = SmartPhone(20000, 'samsung', 13)
s.buy()

# Super Constructor

class Phone:

  def __init__(self, price, brand, camera):
    print('inside phone constructor')
    self.price = price
    self.brand = brand
    self.camera = camera

class SmartPhone(Phone):
  def __init__(self, price, brand, camera, os,ram):
    super().__init__(price, brand, camera)
    self.os = os
    self.ram = ram
    print('inside smartphone constructor')

s = SmartPhone(20000, 'samsung', 12, 'android', 2)

print(s.os)
print(s.brand)

