# -*- coding: utf-8 -*-
"""OOP-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9c7b74zWrnR8x7oa3DuQxQjCmlAmJaD
"""

L =[1,2,3]
L.upper()

s = 'Hello'
s.append()

L=[1,2,3,4,5]
print(type(L))

# Synatax To Createw Object
#objectName = classname()

l= list()
l

# Pascle Case
#HelloWorld

class Atm:

  #constructer(Special Function->SuperPower)
  def __init__(self):
    self.pin = ''
    self.balance = 0
    self.menue()

  def menue(self):
    user_input= input("""
    Hii how can I Help you?
    1. Press 1 to create pin
    2. Press 2 to change pin
    3. Press 3 to check balance
    4. Press 4 to withdraw
    5. Anything else to exit
    """)

    if user_input == '1':
      # Create Pin
      self.create_pin()
    elif user_input == '2':
      # change Pin
      self.change_pin()
    elif user_input == '3':
      # Check Balance
      self.check_balance()
    elif user_input == '4':
      # Withdraw
      self.withdraw()
    else:
      exit()

#Create menue
  def create_pin(self):
    user_pin = input('Enter your pin')
    self.pin = user_pin

    input_balance = int(input('Enter balance'))
    self.balance = input_balance

    print('Pin created Successfully')
    self.menue()

# Change Pin
  def change_pin(self):
    old_pin = input('Enter old pin')
    if old_pin == self.pin:

      # let him change the
      new_pin = input('Enter new pin')
      self.pin = new_pin
      print('Pin change successfully')
      self.menue()

    else:
      print('chal nikal')
      self.menue()

  #check Balance
  def check_balance(self):
    user_pin = input('Enter your pin')
    if user_pin == self.pin:
      print('your balance is ',self.balance)
      self.menue()
    else:
      print('chal nikal')
      self.menue()

      #Withdraw
  def withdraw(self):
    user_pin = input('Enter the pin')
    if user_pin == self.pin:
      amount = int(input('Enter the amount'))
      if amount <= self.balance:
        self.balance = self.balance - amount
        print('Withdrawl Successful')
        print('Remaining Balance',self.balance)
        self.menue()
      else:
        print('Insufficient Balance')
        self.menue()
    else:
      print('chal nikal')
      self.menue()

obj = Atm()

print(type(obj))

# Metode VS Function
l=[1,2,3,4]
len(l) # Function -> bcos it is outside the list class
l.append(2 ) # methode-> bcos it is inside the list class

class temp:
  def __init__(self):
    print('Hello')
obj= temp()

class Fraction:

# Parameterized Constructor
  def __init__(self,x,y):
    self.num = x
    self.dem = y


  def __str__(self):
    return '{}/{}'.format(self.num,self.dem)

  def __add__ (self,other):
     new_num = self.num*other.dem + other.num*self.dem
     new_dem = self.dem*other.dem
     return '{}/{}'.format(new_num,new_dem)

  def __sub__(self,other):
        new_num = self.num*other.dem - other.num*self.dem
        new_dem = self.dem*other.dem
        return '{}/{}'.format(new_num,new_dem)

  def __mul__(self,other):
     new_num = self.num*other.dem * other.num*self.dem
     new_dem = self.dem*other.dem
     return '{}/{}'.format(new_num,new_dem)

  def __truediv__(self,other):
    new_num = self.num*other.dem
    new_dem = self.dem*other.num
    return '{}/{}'.format(new_num,new_dem)

  def convert_to_decimal(self):
    return self.num/self.dem

fr1 = Fraction(3,4)
fr2 = Fraction(1,2)

fr1.convert_to_decimal()

print(fr1+fr2)
print(fr1-fr2)
print(fr1*fr2)
print(fr1/fr2)



