# -*- coding: utf-8 -*-
"""OOP-part-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0X4x1XvUW9UgRLBh1yGqYQ-CrOY2Wo5

## How Objects access Atribute
"""

class Person:

  def __init__ (self,name_input,country_input):
    self .name = name_input
    self.country = country_input

  def greet(self):
    if self.country == 'India':
      print('Namste',self.name)
    else:
      print('Hello',self.name)

# how  to access attributes
p = Person('Ravi','India')

p.name

p.gender

p.gender= 'Male'

p.gender

"""## Reference Variables

- Reference variables hold the objects.
- We can create objects without reference variables as well.
- An object can have multiple reference variables.
- Assigning a new reference variable to an existing object does not create a new object.
"""

# object Without A refrence
class Person:

  def __init__(self):
    self.name = 'Ravi'
    self.gender = 'Male'

p=Person()
q=p

#Multiple Ref
print(id(p))
print(id(q))

# Change attribute value  with the help of 2nd Object

print(p.name)
print(q.name)
q.name = 'Raju'
print(p.name)
print(q.name)

"""# Pass By Reference

## Encpsuletion
# ->Encapsulation is an Object-Oriented Programming (OOP) concept in which data (variables) and the methods (functions) that operate on that data are combined into a single unit called a class, and direct access to the data is restricted to protect it.

# -> Encapsulation means binding data and functions together in a class and hiding the internal data from outside access.
"""

# instance variable -> python tutor
class person:

   def __init__(self,name_input,country_input):
    self.name = name_input
    self.country = country_input

p1= person('Ravi','India')
p2 = person('john','Austrelia')

p1.name

p2.name

class Atm:

  #constructer(Special Function->SuperPower)
  def __init__(self):
    self.pin = ''
    self.___balance = 0
    self.__menue()

  def menue(self):
    user_input= input("""
    Hii how can I Help you?
    1. Press 1 to create pin
    2. Press 2 to change pin
    3. Press 3 to check balance
    4. Press 4 to withdraw
    5. Anything else to exit
    """)

    if user_input == '1':
      # Create Pin
      self.create_pin()
    elif user_input == '2':
      # change Pin
      self.change_pin()
    elif user_input == '3':
      # Check Balance
      self.check_balance()
    elif user_input == '4':
      # Withdraw
      self.withdraw()
    else:
      exit()

#Create menue
  def create_pin(self):
    user_pin = input('Enter your pin')
    self.pin = user_pin

    input_balance = int(input('Enter balance'))
    self.__balance = input_balance

    print('Pin created Successfully')
    self.__menue()

# Change Pin
  def change_pin(self):
    old_pin = input('Enter old pin')
    if old_pin == self.pin:

      # let him change the
      new_pin = input('Enter new pin')
      self.pin = new_pin
      print('Pin change successfully')
      self.__menue()

    else:
      print('chal nikal')
      self.__menue()

  #check Balance
  def check_balance(self):
    user_pin = input('Enter your pin')
    if user_pin == self.pin:
      print('your balance is ',self.__balance)
      self.__menue()
    else:
      print('chal nikal')
      self.__menue()

      #Withdraw
  def withdraw(self):
    user_pin = input('Enter the pin')
    if user_pin == self.pin:
      amount = int(input('Enter the amount'))
      if amount <= self.balance:
        self.__balance = self.__balance - amount
        print('Withdrawl Successful')
        print('Remaining Balance',self.__balance)
        self.__menue()
      else:
        print('Insufficient Balance')
        self.__menue()
    else:
      print('chal nikal')
      self.__menue()

obj.