# -*- coding: utf-8 -*-
"""Opretors In Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19W4mEajzw-xl-QyQlWMdWUeWUZVPk-d6

Operators in Python

*   Arithmetic Operators
*   Relational Operators
*   Logical Operators
*   Bitwise Operators
*   Assignment Operators
*   Membership Operators
"""

# Airthmetic Opertors
a = 10
b = 3
print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division
print(a % b)   # Modulus
print(a ** b)  # Power
print(a // b)  # Floor Division

# Relational (Comparison) Operators
print(a > b)
print(a < b)
print(a == b)
print(a != b)
print(a >= b)
print(a <= b)

# Logical Operators
x = True
y = False
print(x and y)
print(x or y)
print(not x)

# Bitwise Operators
p = 5   # 0101
q = 3   # 0011
print(p & q)   # AND
print(p | q)   # OR
print(p ^ q)   # XOR
print(~p)      # NOT
print(p << 1)  # Left shift
print(p >> 1)  # Right shift

# Assignment Operators
c = 10
c += 5
print(c)
c -= 3
print(c)
c *= 2
print(c)
c /= 4
print(c)

# Membership Operators
list1 = [1, 2, 3, 4]
print(2 in list1)
print(5 not in list1)

# Program - Find the sum of a 3 digit number entered by the user
number = int(input("Enter A 3 Digit Number "))

#345%10->5
a = number%10
number = number//10
#34%10->4
b = number%10
number = number//10
#3%10->3
c = number%10
print(a+b+c)

"""# **if-else Python**"""

# Login Program Indentation (Correct)

email = input("Enter Email: ")
password = input("Enter Password: ")

if email == "ravipathak@gmail.com" and password == "ravi123@":
    print("Welcome To My World")

elif email == "ravipathak@gmail.com" and password != "ravi123@":
    print("Incorrect Password")

    password = input("Enter Password Again: ")

    if password == "ravi123@":
        print("Welcome To My World")
    else:
        print("Beta tumse na ho payega")

else:
    print("Incorrect Credentials")

age = int(input("Enter Your Age "))

if age>=18:
  print("You Can Vote")
else:
  print("You ca't vote")

#min Of 3 Number
a= int(input("first Number"))
b= int(input("Scond Number"))
c= int(input("third Number"))

if a<b and a<c:
  print("Smallest is ",a)
elif b<c:
  print('Smallest is ',b)

else:
  print("Smallest is ",c)

#Menue Driven Calculetor
fnum = int(input("Enter First Number"))
op = input("Enter The Operation")
snum = int(input("Enter Second Number"))



if op =='+':
  print(fnum + snum)
elif op== "-":
  print(fnum-snum)
elif op=="*":
  print(fnum*snum)

elif op=="/":
  print(fnum/snum)
else:
  print(fnum%snum)

# Menu Driven ATM Program using if-else

balance = 10000

print("----- ATM MENU -----")
print("1. Check Balance")
print("2. Deposit Money")
print("3. Withdraw Money")
print("4. Exit")

choice = int(input("Enter your choice: "))

if choice == 1:
    print("Your Balance is:", balance)

elif choice == 2:
    amount = int(input("Enter deposit amount: "))
    balance = balance + amount
    print("Money Deposited Successfully")
    print("Updated Balance:", balance)

elif choice == 3:
    amount = int(input("Enter withdraw amount: "))
    if amount <= balance:
        balance = balance - amount
        print("Please collect your cash")
        print("Remaining Balance:", balance)
    else:
        print("Insufficient Balance")

elif choice == 4:
    print("Thank you for using ATM")

else:
    print("Invalid Choice")

"""# Modules In Python


*   math
*   Keyword

*   datetime
*   Random





"""

import math
number = int(input("Enter a Number"))
math.factorial(number)
print(number," Factorial Is:",math.factorial(number))

#keyword
import keyword
print(keyword.kwlist)

#random
import random
print(random.randint(1,100))

import datetime
print(datetime.datetime.now())

import sys
!{sys.executable} -m pip install black isort hypothesis
help('modules')

"""## Loops In Python


*   Need of Loop
*   for loop

*   while loop





"""

# While loop example -> program to print the table
# Program -> Sum of all digits of a given number
# Program -> keep accepting numbers from users till he/she enters a 0 and then find the avg

# While loop example -> program to print the table
number = int(input("Enter The Numer:"))

i = 1

while i<11:
  print(number,"*",i,"=",number*i)
  i +=1

#While Loop with if -else
x=1
while x<5:
  print(x)
  x+=1
else:
  print("Limit Crossed")

# for Loop demo
for i in range(0,11):
  print(i)

"""# Program - The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. You have to write a program to find out the population at the end of each of the last 10 years."""

#useing Third Variable
a = int(input("Enter a number: "))
b = int(input("Enter b number: "))

temp = a
a = b
b = temp

print("After Swapping:")
print("a =", a)
print("b =", b)

# Without Third Variable
a = int(input("Enter a number: "))
b = int(input("Enter b number: "))

a,b=b,a

print("After Swapping:")
print("a =", a)
print("b =", b)

"""## Nested loops"""

# Example -> unique pair
for i in range(1,5):
  for j in range(1,5):
    print(i,j)

"""# Pattern 1"""

# Code here
rows = int (input("Enter The Number Of Rowas:"))
for i in range(1,rows+1):
  for j  in range(1,i+1):
    print('*',end="")

  print()

for i in range(1,5):
  for j in range(1,i+1):
    print("*",end="")

  print()

for i in range(1,5):
  for j in range(1,i+1):
    print(i,end="")

  print()

for i in range(1,5):
  for j in range(1,i+1):
    print(j,end="")

  print()

rows = int (input("Enter The Number Of Rowas:"))
for i in range (1,rows+1):
  for j in range(1,i+1):
    print(j,end="")
  for k in range(i-1,0,-1):
      print(k,end="")
  print()

"""# Loops Staetment
*   Break
*   Continue


*   Pass

> Control the execution of Loop









"""

# Break Stetment
for i in range (1,20):
  if i == 10:
    break
  print(i)

#Brek Example
lower = int(input("Enter Lower Range:"))
upper = int(input("Enter Upper Range:"))

for i in range(lower,upper+1):
  for j in range(2,i):
    if i%j == 0:
      break

  else:
    print(i)

# Continue-> Iteretion Skip
for i in range(1,10):
  if i == 5:
    continue
  print(i)

# pass
for i in range(1,10):
  pass

