# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irOQq5DSszt5i3gMfejLt75UuBFVT-PT

# Strings

Strings are a sequence of characters.

In Python specifically, strings are a sequence of Unicode characters.

## Topics Covered:
- Creating Strings
- Accessing Strings
- Adding Characters to Strings
- Editing Strings
- Deleting Strings
- Operations on Strings
- String Functions

# Creating Strings
"""

r='hello'
r="hello"
#Multiple String
r='''hello'''
r="""Hello"""
s=str('hello')
print(r)

"'it's rainin outside"

"""# Accessing Substrings From a Strings"""

#  Positive Indexing
r='Helo World'
print(r[4])

# Negative Indexing
r="Helloworld"
print(r[-3])

#Slicing
s='hello world'
print(s[0:5])
print(s[2:])
print(s[:3])
print(s[2:3:2])
print(s[2:3])

print(s[::-1])

"""# Editing Aad Deleting Strings"""

S= 'hello world'
S[0]="h"

#python String Are Immutable

s="hello World"
del s
print(s)

"""## Operations on Strings

- Arithmetic Operations
- Relational Operations
- Logical Operations
- Loops on Strings
- Membership Operations

"""

print("Delhi"+" "+"Mumbai")

print("Delhi"*5)

print("#"*100)

"Delhi" == "Mumbai"

"Mumbai" > "pune"
# lexiographically

'hello' and "world"

'hello' or 'world'

'' and 'world'

'' or 'world'

not 'hello'

for i in 'hello':
  print(i)

for i in 'delhi':
  print('pune')

'D' in 'Delhi'

"""## Common Functions

- len()
- max()
- min()
- sorted()

"""

len('hello world')

max('hello world')

min('hello world')

sorted('hello world')

"""## String Methods

- capitalize()
- title()
- upper()
- lower()
- swapcase()

"""



s='hello world'
s.capitalize()

s.title()

s.upper()

s.lower()

'HeLlo WorLD'.swapcase()



"""## String Methods

- count()
- find()
- index()

"""

'my name is Ravi'.count('a')

'my name is ravi'.find('is')

'my name is ravi'.index('is')

'my name is ravi'.index('x')

"""## String Methods

- startswith()
- endswith()

"""

'my name is ravi'.endswith('vi')

'my name is ravi'.startswith('my')

"""# Format"""

name= 'Ravi'
gender='male'

'Hi my name is {} and I am a {}'.format(name,gender)

"""## String Methods

- isalnum()
- isalpha()
- isdigit()
- isidentifier()

"""

'ravi1234'.isalnum()

'ravi'.isalpha()

'123456'.isdigit()

'name1'.isidentifier()

"""# Split/Join"""

'hi my name is ravi'.split()

' '.join(['hi', 'my', 'name', 'is', 'ravi'])

"""# Repalce"""

'hi my name is ravi'.replace('ravi','Data Scientist')

"""**Strip**"""

'ravi                     '.strip()

