# -*- coding: utf-8 -*-
"""Tupple_Sets_Dictonary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUz5OzLE6Xo3XnSRFskx6RBfcHJTWlbW

## Tuples

A tuple in Python is similar to a list. The difference between the two is that we cannot change the elements of a tuple once it is assigned whereas we can change the elements of a list.

In short, a tuple is an immutable list. A tuple can not be changed in any way once it is created.

### Characteristics

- Ordered
- Unchangeable
- Allows duplicate

## Plan of attack

- Creating a Tuple
- Accessing items
- Editing items
- Adding items
- Deleting items
- Operations on Tuples
- Tuple Functions
"""

#Empty
t1=()
print(t1)
# create a tuple with a single item
t2=(2) #int
print(type(t2))
t2=('hello') #str
print(type(t2))

t2=('hello',) #tuple
print(type(t2))

t3 = (1,2,3,4,5) #Homoginious
print(t3)

#Hetroginious
t3 =(1,'Ravi',3.5,True,4+5j)
print(t3)

t4= (1,2,3,(4,5))
print(t4)

# using type conversion
t5= tuple('Ravi')
print(t5)

"""Acessinng Item In Tuple


*   indexing
*   Slicing


"""

# Indexing
t6 = (1,2,3,4,5,6,7,8,9,10)
print(t6[0])

#Slicing
print(t6[0:5])
print(t6[1:7:2])

"""# Editing Item"""

# 'tuple' object does not support item assignment
t6
t6[1]=1000
#immuntable just like string

"""# Adding Item"""

print(t3)
#immuntable just like string

"""# Deleting Item"""

t7 =(1,2,3,4,5)

print(t7)
del t7
print(t7)

"""Operteion On Tuple"""

# + and *
t1 = (1, 2, 3, 4)
t2 = (5, 6, 7, 8)

print(t1 + t2)

print(t1 * 3)

# membership
1 in t1

# iteration
for i in t1:
    print(i)

"""Function On Tuple"""

# len/sum/min/max/sorted
t = (1, 2, 3, 4)

len(t)

sum(t)

min(t)

max(t)

#sorted(t, reverse=True)

#  count
t8 =(1,2,3,4,5,6,7,8,5,4,6)
t8.count(5)

#index
t8.index(8)

"""## Difference Between Lists and Tuples

### 1. Syntax
- List: Uses square brackets []
  Example: L = [1, 2, 3]

- Tuple: Uses parentheses ()
  Example: T = (1, 2, 3)

---

### 2. Mutability
- List: Mutable (elements can be modified after creation)
  Example:
  L = [1, 2, 3]
  L[0] = 10

- Tuple: Immutable (elements cannot be modified after creation)
  Example:
  T = (1, 2, 3)
  # T[0] = 10  → Error

---

### 3. Speed
- List: Slightly slower compared to tuples.
- Tuple: Faster because they are immutable.

---

### 4. Memory
- List: Consumes more memory.
- Tuple: Consumes less memory than lists.

---

### 5. Built-in Functionality
- List: Has more built-in methods (append, remove, pop, sort, etc.)
- Tuple: Has fewer built-in methods (mainly count and index).

---

### 6. Error Prone
- List: More error-prone because elements can be modified accidentally.
- Tuple: Safer since elements cannot be changed.

---

### 7. Usability
- List: Used when data needs to be modified frequently.
- Tuple: Used when data should remain constant and unchanged.
"""

# Speed Exampel
import time

L = list(range(10000000))
T = tuple(range(10000000))

start = time.time()
for i in L:
    i * 5
print('List time', time.time() - start)

start = time.time()
for i in T:
    i * 5
print('Tuple time', time.time() - start)

# Memory example
import sys
L = list(range(1000))
T = tuple(range(1000))

print('List size: ', sys.getsizeof(L))
print('Tuple size: ', sys.getsizeof(T))

a=[1,2,3,4]
b=a
a.append(5)
print(a)
print(b)

a=(1,2,3)
b=a
a=a+(4,)
print(a)
print(b)

"""Why Use Tuple

Special Syntax
"""

#tuple unpacking
a,b,c=(1,2,3)
print(a,b,c)

#Swap
a=1
b=2
a,b=b,a
print('a:',a,'b:',b)

a,b,*others=(1,2,3,4,5)
print(a,b)
print(others)

#Ziping tuples
a=(1,2,3)
b=(4,5,6)
zip(a,b)

"""## Sets

A set is an unordered collection of items. Every set element is unique (no duplicates) and must be immutable (cannot be changed). However, a set itself is mutable. We can add or remove items from it.

Sets can also be used to perform mathematical set operations like union, intersection, symmetric difference, etc.

### Characteristics:

- Unordered
- Mutable
- No Duplicates
- Can't contain mutable data types
"""

# empty
s = set()
print(s)
print(type(s))

# 1D and 2D
s1 = {1, 2, 3}
print(s1)

# s2 = {1,2,3,{4,5}}
# print(s2)

# homo and hetro
s3 = {1, 'hello', 4.5, (1, 2, 3)}
print(s3)

# using type conversion
s4 = set([1, 2, 3])
print(s4)

# duplicates not allowed
s5 = {1, 1, 2, 2, 3, 3}
print(s5)

# set can't have mutable items
# s6 = {1, 2, [3, 4]}
# print(s6)

s1={1,2,3}
s2={3,2,1}
print(s1 == s2)

"""# Acessing Item"""

s1={1,2,3,4,5}
s1[0]
s1[0:3]

"""# Editing Item"""

s1={1,2,3,4,5}
s1[0]=100

"""# Adding Item"""

S={1,2,3,4}
#add
S.add(5) #One Item Add
print(S)
#update
S.update([6,7,8]) #Multiple item add
print(S)

"""# Deleting Item"""

#del
# s9={1,2,3,4,5}
# print(s9)
# del s9
# print(s9)
# discard
# s10={1,2,3,4,5}
# s10.discard(2)
# print(s10)

#remove
# s11={1,2,3,4,5}
# s11.remove(2)
# print(s11)

#pop
# s12={1,2,3,4,5}
# s12.pop()
# print(s12)

#clear
s12.clear()
print(s12)

"""# Set Opretion"""

s3={1,2,3,4,5}
s4={6,4,7,8,9,10}
#union(|)
s3 | s4

#Inersection(&)
s3 & s4

#difference(-)
s3 - s4
s4 - s3

#Symentric Difference(^)
s3 ^ s4

#membership test
1 in s3
1 not in s3

#iteration
for i in s3:
  print(i)

"""# Set Function"""

# len/sum/min/max/sorted

s5={1,2,3,4,5}
len(s5)
sum(s5)
min(s5)
max(s5)
sorted(s5,reverse=True)

# union / update
s6={1,2,3,4,5}
s7={6,7,8,9,10}
s6.union(s7)
print(s6)
s6.update(s7)
print(s6)
print(s7)

# intesetion / intersection_update
s8={1,2,3,4,5}
s9={4,5,6,7,8}
s8.intersection(s9)

s8.intersection_update(s9)
print(s8)
print(s9)

# differnce /difference_update
s10={1,2,3,4,5}
s11={4,5,6,7,8}

s10.difference(s11)

s10.difference_update(s11)
print(s10)
print(s11)

# Symmetric_differnce /symmetric_difference_update
s10={1,2,3,4,5}
s11={4,5,6,7,8}

s10.symmetric_difference(s11)

s10.symmetric_difference_update(s11)
print(s10)
print(s11)

# isdisjoint/issubset/issuperset
s12={1,2,3,4}
s13={5,6,7,8}
s12.isdisjoint(s13)

s14={1,2,3,4,5}
s15={3,4,5}
s15.issubset(s14)

s14.issuperset(s15)

#copy
s17={1,2,3,4,5}
s18=s17.copy()
print(s17)
print(s18)

"""# Frozenset
Frozen set is just an immutable version of a python


"""

#Create frozenset

fs= frozenset([1,2,3,4])
print(fs)
print(type(fs))

# what works and what does not
# works > all read function
# does'nt work > write operretion

#when to use
# 2d sets
fs= frozenset([1,2,frozenset([3,4])])
fs

"""Set comprihension"""

{ i for i in range(1,11)}

"""## Dictionary

Dictionary in Python is a collection of keys values, used to store data values like a map, which, unlike other data types which hold only a single value as an element.

In some languages it is known as map or associative arrays.

dict = {'name' : 'nitish', 'age' : 33, 'gender' : 'male'}

### Characteristics:

- Mutable
- Indexing has no meaning
- keys can't be duplicated
- keys can't be mutable items

## Create Dictionary
"""

# empty
d={}
d
# 1d Dictionary
d1 = {'name': 'ravi',  'gender': 'male'}
d1


# with mixed keys
d2 = {'name': 'ravi',  'gender': 'male', 'age': 22}
d2

# 2d dictionary
d3 = {
    'name': 'ravi',
    'gender': 'male',
    'age': 22,
    'address': {
        'city': 'delhi',
        'state': 'delhi'
    }
}
d3


# using sequence and dict function
d4=dict([(1,1),(2,2),(3,3)])
d4
#duplicate keys
d5={'name':'nitish','name':'ravi'}
d5


# mutable keys
# d6={'name':'nitish',[1,2,3]:2}
# d6

d3['address']['city']

"""# Accessing Element"""

my_dict = {'name':'Jack','age':15}
#[]
my_dict['name']
my_dict['age']
#get
my_dict.get('name')
my_dict.get('age')

"""Adding key-value pair"""

student={'name':'ravi',
         'Department':'BCA',
         'College':'MMDU',
         'sem':6,
         'Subjects':{'Machine Learning':78,'Data Visualization':89,'R Program':90}}
# student['Subjects']['R Program']
student['Subjects']['Data Science']=95
del student['Subjects']['R Program']
student

my_dict['gender']='male'
my_dict
my_dict['weight']=80
my_dict

"""# **Ramove Key value pair**"""

d={'name': 'Jack', 'age': 15,3:3, 'gender': 'male', 'weight': 80}
# Pop
d.pop(3)
print(d)
#popitem
# d.popitem()
# print(d)
#del
# del d['name']
# print(d)

#clear
# d.clear()
# print(d)
print(d)

"""# **Editing Key-value pair**"""

student['sem']=7
student['Subjects']['Machine Learning']=80
student

"""# **Dictionary Operation**


*   Membership
*   iteretion


"""

print(student)

'ravi' in student
'name' in student
'ravi' not in student

d= {'name':'ravi','gender':'male'}

for i in d:
  print(i,d[i])

"""## Dictionary function"""

# len/sorted
# len(student)
# # print(student)
# sorted(student,reverse=True)
# print(student)
min(student)
max(student)

# item /key/value
print(d)
print(d.items())
print(d.keys())
print(d.values())

# upadate
d1={1:2,3:3,4:5,}
d2={6:7,8:9}
d1.update(d2)
print(d1)
print(d2)

"""# **Dictionary Comprihension**"""

# print 1st 10 numbertas and thier squares
{i:i**2 for i in range(1,11)}

#usin existin dict
distence ={'delhi':1000,'mumbai':2000,'chennai':3000}
{key:value*0.62 for (key,value) in distence.items() }

# using zip
days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
temp_c=[30.5,32.6,37.7,34.6,46.1,23.5,43.5]

{key:value for (key,value) in zip(days,temp_c)}

# using if condition
products={'phone':10,'laptop':0,'charger':32,'tablet':0}

{key:value for (key,value) in products.items() if value>0}

# Commented out IPython magic to ensure Python compatibility.
TOKEN = "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"

!rm -rf Data-Science-Mentorship-Programme-

# Clone
!git clone https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

# %cd Data-Science-Mentorship-Programme-

# Copy notebook
!cp /content/Tupple_Sets_Dictionary.ipynb .

# Git config
!git config user.email "pathakravi.en@gmail.com"
!git config user.name "Engineer-ravi"

# Add & Commit
!git add .
!git commit -m "Added Tupple_Sets_Dictionary notebook"

# Push
!git push https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

!rm -rf Data-Science-Mentorship-Programme-

!git clone https://github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

!rm -rf Data-Science-Mentorship-Programme-

!git clone https://github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

TOKEN = "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"

# Initialize git in current Colab directory
!git init

# Add remote repo
!git remote add origin https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

# Configure git
!git config user.email "pathakravi.en@gmail.com"
!git config user.name "Engineer-ravi"

# Add notebook file
!git add Tupple_Sets_Dictionary.ipynb

# Commit
!git commit -m "First commit from Colab"

# Set branch to main
!git branch -M main

# Push
!git push -u origin main

TOKEN = "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"

# Initialize git
!git init

# Add remote
!git remote remove origin 2> /dev/null
!git remote add origin https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

# Configure git
!git config user.email "pathakravi.en@gmail.com"
!git config user.name "Engineer-ravi"

# Add correct file path
!git add /content/Tupple_Sets_Dictionary.ipynb

# Commit
!git commit -m "First commit from Colab"

# Rename branch
!git branch -M main

# Push
!git push -u origin main

!ls

!ls /content

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!ls "/content/drive/MyDrive/Colab Notebooks"

TOKEN = "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"

# Initialize git
!git init

# Remove old remote if exists
!git remote remove origin 2> /dev/null

# Add GitHub repo
!git remote add origin https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

# Configure git
!git config user.email "pathakravi.en@gmail.com"
!git config user.name "Engineer-ravi"

# Copy notebook from Drive to current folder
!cp "/content/drive/MyDrive/Colab Notebooks/Tupple_Sets_Dictionary.ipynb" .

# Add file
!git add Tupple_Sets_Dictionary.ipynb

# Commit
!git commit -m "First commit from Colab"

# Rename branch
!git branch -M main

# Push
!git push -u origin main

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks"
!pwd
!ls

TOKEN = "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"

!git init
!git remote remove origin 2> /dev/null
!git remote add origin https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

!git config user.email "pathakravi.en@gmail.com"
!git config user.name "Engineer-ravi"

!git add Tupple_Sets_Dictionary.ipynb
!git commit -m "First commit from Colab"
!git branch -M main
!git push -u origin main

!git add .

!git commit -m "First commit from Colab"

!git branch -M main

!git push -u origin main

!git remote -v

TOKEN = "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"


!git remote remove origin

!git remote add origin https://Engineer-ravi:$TOKEN@github.com/Engineer-ravi/Data-Science-Mentorship-Programme-.git

!git push -u origin main

